version: "3"

services:
    postgres:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - movie-api

networks:
    movie-api :
